/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.users;

/**
 *
 * @author CUI
 */
public class librarianfunctionalitypage extends javax.swing.JFrame {

    /**
     * Creates new form librarianfunctionalitypage
     */
    public librarianfunctionalitypage() {
        initComponents();
       addbook.addActionListener(e -> {
           addBook add = new addBook();
            add.setVisible(true);
            add.pack();
      add.setLocationRelativeTo(null);
      add.setDefaultCloseOperation(Registrationform.EXIT_ON_CLOSE);
      this.dispose();
        });
        deletebook.addActionListener(e -> {
          deletebook delete = new deletebook();
            delete.setVisible(true);
            delete.pack();
      delete.setLocationRelativeTo(null);
      delete.setDefaultCloseOperation(Registrationform.EXIT_ON_CLOSE);
      this.dispose();
        });
        finebutton.addActionListener(e -> {
          fine fine = new fine();
            fine.setVisible(true);
            fine.pack();
      fine.setLocationRelativeTo(null);
      fine.setDefaultCloseOperation(Registrationform.EXIT_ON_CLOSE);
      this.dispose();
        });
          logout.addActionListener(e -> {
         mainloginpage main = new mainloginpage();
           main.setVisible(true);
            main.pack();
      main.setLocationRelativeTo(null);
      main.setDefaultCloseOperation(Registrationform.EXIT_ON_CLOSE);
      this.dispose();
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        addbook = new javax.swing.JButton();
        deletebook = new javax.swing.JButton();
        orderbook = new javax.swing.JButton();
        finebutton = new javax.swing.JButton();
        checkdetailsbook = new javax.swing.JButton();
        allbookspage = new javax.swing.JButton();
        logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(123, 201, 193));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LIBRARIAN SECTION");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 17, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 18, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 60));

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));

        addbook.setBackground(new java.awt.Color(123, 201, 193));
        addbook.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addbook.setForeground(new java.awt.Color(255, 255, 255));
        addbook.setText("Add book");

        deletebook.setBackground(new java.awt.Color(123, 201, 193));
        deletebook.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deletebook.setForeground(new java.awt.Color(255, 255, 255));
        deletebook.setText("Delete book");

        orderbook.setBackground(new java.awt.Color(123, 201, 193));
        orderbook.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        orderbook.setForeground(new java.awt.Color(255, 255, 255));
        orderbook.setText("Order book");

        finebutton.setBackground(new java.awt.Color(123, 201, 193));
        finebutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        finebutton.setForeground(new java.awt.Color(255, 255, 255));
        finebutton.setText("Generate fine");

        checkdetailsbook.setBackground(new java.awt.Color(123, 201, 193));
        checkdetailsbook.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        checkdetailsbook.setForeground(new java.awt.Color(255, 255, 255));
        checkdetailsbook.setText("Check details");

        allbookspage.setBackground(new java.awt.Color(123, 201, 193));
        allbookspage.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        allbookspage.setForeground(new java.awt.Color(255, 255, 255));
        allbookspage.setText("Show all books");

        logout.setBackground(new java.awt.Color(123, 201, 193));
        logout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("Logout");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(allbookspage)
                        .addContainerGap(129, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deletebook, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(orderbook, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkdetailsbook, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(finebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(logout)
                        .addGap(157, 157, 157))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(addbook, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(133, 133, 133))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(addbook)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deletebook)
                    .addComponent(finebutton))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orderbook)
                    .addComponent(checkdetailsbook))
                .addGap(18, 18, 18)
                .addComponent(allbookspage)
                .addGap(18, 18, 18)
                .addComponent(logout)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 400, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(librarianfunctionalitypage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(librarianfunctionalitypage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(librarianfunctionalitypage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(librarianfunctionalitypage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new librarianfunctionalitypage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbook;
    private javax.swing.JButton allbookspage;
    private javax.swing.JButton checkdetailsbook;
    private javax.swing.JButton deletebook;
    private javax.swing.JButton finebutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton logout;
    private javax.swing.JButton orderbook;
    // End of variables declaration//GEN-END:variables
}
